# Generated by Django 2.2.19 on 2025-01-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe_ingredient',
            name='amount',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
