# Generated by Django 2.2.19 on 2025-01-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipt', '0002_auto_20250128_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.IntegerField(blank=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(blank=True, max_length=200, verbose_name='Единица измерения'),
        ),
    ]
