# Generated by Django 2.2.19 on 2025-01-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipt', '0003_auto_20250129_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.IntegerField(default='12', verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(default='г', max_length=200, verbose_name='Единица измерения'),
        ),
    ]
