# Generated by Django 2.2.19 on 2025-01-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipt', '0004_auto_20250129_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
        migrations.AddField(
            model_name='recipe_ingredient',
            name='amount',
            field=models.IntegerField(default='12', verbose_name='Количество'),
        ),
    ]
