# Generated by Django 2.2.19 on 2025-01-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipt', '0005_auto_20250131_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe_ingredient',
            name='amount',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.IntegerField(default='12', verbose_name='Количество'),
        ),
    ]
