# Generated by Django 2.2.19 on 2025-01-31 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipt', '0006_auto_20250131_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
        migrations.AddField(
            model_name='recipe_ingredient',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
