# Generated by Django 2.2.19 on 2025-02-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipt', '0009_comment_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
