# Generated by Django 2.2.19 on 2025-02-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipt', '0011_auto_20250206_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation',
            name='estimation',
            field=models.CharField(max_length=1),
        ),
    ]
