# Generated by Django 2.2.19 on 2025-02-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipt', '0012_auto_20250206_0349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='texts',
        ),
    ]
