# Generated by Django 2.2.19 on 2025-02-08 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipt', '0013_auto_20250206_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe_to_posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currents', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
                ('selected_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecteds', to='recipt.Post', verbose_name='Подписка на пост')),
            ],
        ),
    ]
