# Generated by Django 2.2.19 on 2025-02-08 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipt', '0014_subscribe_to_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe_to_posts',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='f', to=settings.AUTH_USER_MODEL, verbose_name='Создатель постов'),
            preserve_default=False,
        ),
    ]
