# Generated by Django 2.2.19 on 2025-02-10 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipt', '0016_auto_20250210_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='texts',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='subscribetopost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='recipt.Post', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='subscribetopost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
    ]
