# Generated by Django 2.2.19 on 2025-02-10 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipt', '0018_auto_20250210_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipt', to='recipt.Ingredient', verbose_name='Ингредиент'),
        ),
    ]
