# Generated by Django 2.2.19 on 2025-02-11 19:21

from django.db import migrations, models
import recipt.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipt', '0019_auto_20250210_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=200, validators=[recipt.validators.validate_not_empty], verbose_name='Название'),
        ),
    ]
