# Generated by Django 2.2.19 on 2025-02-11 19:51

from django.db import migrations, models
import recipt.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipt', '0020_auto_20250211_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cooking_time',
            field=models.IntegerField(help_text='Укажите время в минутах', validators=[recipt.validators.validate_non_negative], verbose_name='Время приготовления, мин'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=200, validators=[recipt.validators.validate_not_empty, recipt.validators.validate_capitalized], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Укажите количество ингредиента', validators=[recipt.validators.validate_non_negative], verbose_name='Количество'),
        ),
    ]
