# Generated by Django 2.2.19 on 2025-02-12 14:24

from django.db import migrations, models
import django.db.models.deletion
import recipt.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipt', '0021_auto_20250211_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Легко', max_length=40, verbose_name='Название')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='cooking_time',
            field=models.IntegerField(help_text='Укажите время в минутах', validators=[recipt.validators.validate_non_negative, recipt.validators.validate_not_empty], verbose_name='Время приготовления, мин'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(validators=[recipt.validators.validate_not_empty, recipt.validators.validate_capitalized], verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='recipt.Tags', verbose_name='сложность'),
        ),
    ]
